### ISSUE TITLE
How to properly use an invocable method with SOQL as source?

### ISSUE THREAD

**Issue by renatoliveira** [douglascayers-org/sfdx-mass-action-scheduler#102]
Note: I'm creating this issue with the documentation type because it probably is related to misuse instead of an actual error. 

## Is your documentation request related to an existing wiki page? If yes, which pages?

It is related to how to use invocable apex as target for an action.

https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Invocable-Apex-Actions

## Describe the documentation change you're offering or requesting.

I'm asking for a documentation on this because I tried to set it up and couldn't figure out why the variable of my invocable method is `null` when running.

As an example:

SOQL query:

```soql
SELECT Id, NumberOfEmployees FROM Account
```

Invocable method:

```apex
public with sharing class ReplaceEmployeeCount {

    @InvocableMethod(label='Replace test')
    public static void doThing (List<Account> inputs) {
        System.debug(inputs);
        for (Account record : inputs) {
            record.NumberOfEmployees = 0;
        }
        update inputs;
    }
}
```

That `.debug` shows as:

```
09:54:41:002 USER_DEBUG [5]|DEBUG|(null)
```

While on the MA_MassActionUtils class, the requests are shown as:

```
09:54:41:039 USER_DEBUG [993]|DEBUG|System.HttpRequest[Endpoint=https://computing-efficiency-1553-dev-ed.cs2.my.salesforce.com/services/data/v45.0/actions/custom/apex/ReplaceEmployeeCount, Method=POST]
09:54:41:039 USER_DEBUG [994]|DEBUG|{
09:54:41:000 USER_DEBUG   "inputs" : [ { } ]
09:54:41:000 USER_DEBUG }
09:54:41:093 USER_DEBUG [998]|DEBUG|System.HttpResponse[Status=Bad Request, StatusCode=400]
09:54:41:093 USER_DEBUG [999]|DEBUG|[{"actionName":"ReplaceEmployeeCount","errors":[{"statusCode":"UNKNOWN_EXCEPTION","message":"An Apex error occurred: System.NullPointerException: Attempt to de-reference a null object","fields":[]}],"isSuccess":false,"outputValues":null}]
```

Do I have to define an InvocableVariable to receive the records? 🤔

If I add an inner class with an invocable variable, like this:

```apex
public with sharing class ReplaceEmployeeCount {

    @InvocableMethod(label='Replace test')
    public static void doThing (List<ReplaceEmployeeCountInput> inputs) {
        System.debug(inputs);
        List<Account> accounts = new List<Account>();
        for (ReplaceEmployeeCountInput input : inputs) {
            Account record = input.record;
            record.NumberOfEmployees = 0;
            accounts.add(record);
        }
        update accounts;
    }

    public class ReplaceEmployeeCountInput {
        @InvocableVariable
        public Account record;
    }
}
```

Then I still get a null value, because the configuration does not allow me to select a target.

```
10:09:39:003 USER_DEBUG [5]|DEBUG|(ReplaceEmployeeCountInput:[record=null])
```

What might I be doing wrong? Or have I just discovered an issue?

**Comment by douglascayers** [comment]
Hi @renatoliveira, thank you for your question and your interest in using Mass Action Scheduler.

You've provided great details here in your question; I appreciate being able to follow your thought process and what you've tried.

You are on the right track with `@InvocableVariable`; however, you'll need an invocable variable per field you want to map from Mass Action Scheduler **and** the variables should match the data type of the fields from your data source.

In short, instead of:

```apex
    public class ReplaceEmployeeCountInput {
        @InvocableVariable
        public Account record;
    }
```

You'd need:

```apex
    public class ReplaceEmployeeCountInput {
        @InvocableVariable
        public ID accountId;
        @InvocableVariable
        public Integer numberOfEmployees;
    }
```

In your `@InvocableMethod` method, you would iterate your list of inputs and collect the `accountId`s so that you can efficiently make a single SOQL query to retrieve any related account fields (or other objects) that were not mapped from your data source.

Putting all that together, I'd modify your original example to be like this:

```apex
public with sharing class ReplaceEmployeeCount {

    @InvocableMethod(label='Replace test')
    public static void doThing (List<ReplaceEmployeeCountInput> inputs) {
        System.debug(inputs);
        Set<ID> accountIds = getAccountIds(inputs);
        List<Account> accounts = [
            SELECT Id, NumberOfEmployees
            FROM Account
            WHERE Id IN :accountIds
        ];
        for (Account acct : accounts) {
            acct.NumberOfEmployees = 0;
        }
        update accounts;
    }

    public class ReplaceEmployeeCountInput {
        @InvocableVariable
        public ID accountId;
        @InvocableVariable
        public Integer numberOfEmployees; // or other data from your data source
    }

    private static Set<ID> getAccountIds(List<ReplaceEmployeeCountInput> inputs) {
        Set<ID> accountIds = new Set<ID>();
        for (ReplaceEmployeeCountInput input : inputs) {
            if (String.isNotBlank(input.accountId)) {
                accountIds.add(input.accountId);
            }
        }
        return accountIds;
    }
}
```

In this specific example, since the Apex code is so trivial--it might not be in practice, but let's assume for argument's sake that the Apex code you want to run is this trivial--then you could use the [Anonymous Apex](https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Anonymous-Apex-Actions) action and not deploy any Apex class or test to your org at all.

```apex
void execute(List<Map<String, Object>> sourceRecordsBatch) {
    Set<ID> accountIds = getAccountIds(inputs);
    List<Account> accounts = [
        SELECT Id, NumberOfEmployees
        FROM Account
        WHERE Id IN :accountIds
    ];
    for (Account acct : accounts) {
        acct.NumberOfEmployees = 0;
    }
    update accounts;
}

Set<ID> getAccountIds(List<Map<String, Object>> inputs) {
    Set<ID> accountIds = new Set<ID>();
    for (Map<String, Object> input : inputs) {
        if (String.isNotBlank(input.get('Id')) {
            accountIds.add(input.get('Id'));
        }
    }
    return accountIds;
}
```

In this specific example, since the Apex code is so trivial--it might not be in practice, but let's assume for argument's sake that the Apex code you want to run is this trivial--then you could use the [Quick Action](https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Quick-Action-Actions) action of type **Update a Record** and not deploy any Apex class or test to your org at all.

Your Quick Action defined on the Account object would set a predefined value for the `NumberOfEmployees` field and set its default value to `0`. In your Field Mappings step, you'd just map the Account ID from your data source to the Record ID of the Quick Action.

**Comment by renatoliveira** [comment]
Ah yes, it is a trivial snippet because I just wanted to know how it would work. Definitely would choose another method to do something as simple as that. To be honest I'm interested in that issue about monitoring the batch's progress, so first I needed something to run.

Thank you very much for your reply.

**Comment by douglascayers** [comment]
I've updated the documentation based on this discussion, https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Invocable-Apex-Actions
