### ISSUE TITLE
Sandbox: Package Mass Action Scheduler Install Failed

### ISSUE THREAD

**Issue by cchrisv** [douglascayers-org/sfdx-mass-action-scheduler#109]
## Version of Mass Action Scheduler

2.3

## Steps To Reproduce

1. Attempt installation into a sandbox

## Expected Behavior

Successful instalation

## Actual Result

Your request to install package "Mass Action Scheduler 2.3" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.

1. (Mass_Action_Scheduler_Lightning) Small is not a supported form factor.
Mass_Action_Scheduler_Lightning: Small is not a supported form factor.

2. (Mass_Action_Configuration__c) Small is not a supported form factor.
Mass_Action_Configuration__c: Small is not a supported form factor.

3. (Mass_Action_Log__c) Small is not a supported form factor.
Mass_Action_Log__c: Small is not a supported form factor.

## Source Type

- [ ] Reports
- [ ] List Views
- [ ] SOQL Queries

## Action Type

- [ ] Process Builder & Flows
- [ ] Workflow Rules
- [ ] Email Alerts
- [ ] Quick Actions
- [ ] Apex

**Comment by jensanald** [comment]
@doug  I also tried to install; upgrade from 2.2 to 2.3 in sandbox and I received the following error.

This app can't be upgraded
(Mass_Action_Test_Named_Credential) Cannot Modify Managed Component
The component you are attempting to modify is part of a managed package, and cannot be modified.

**Comment by douglascayers** [comment]
Strange, I've upgraded the package from 2.1 => 2.2 => 2.3 multiple times in scratch orgs, each time with pre-existing data to confirm the post install scripts worked.

Off the top of my head I'm not sure what the issue is since I've not encountered it yet.

Anyone willing to share with me credentials to a sandbox that I can troubleshoot with?

**Comment by douglascayers** [comment]
@cchrisv @jensanald By chance, have you all made any customizations to the objects, pages, components, anything that came bundled with the package? For example, customized any page layouts or related lists or Lightning Pages?

🤔 I'm trying to guess at what might be limiting the upgrade for you all

**Comment by cchrisv** [comment]
I did not customize anything that comes with the package.
I can provide you with a temporary login. What is your email and I'll setup an user.

**Comment by douglascayers** [comment]
Thanks, @cchrisv. My email is my [GitHub username](https://github.com/douglascayers) at gmail.

**Comment by jensanald** [comment]
I can share my sandbox credentials. How should I send them privately. BtW-
I was able to successfully upgrade from 1.5 to 2.3 in my dev org.

**Comment by douglascayers** [comment]
Thanks, @jensanald. My email is my [GitHub username](https://github.com/douglascayers) at gmail.

**Comment by douglascayers** [comment]
@cchrisv thanks for the sandbox access. One difference I noticed was in Setup | App Manager | Mass Action (Lightning) app.

In your sandbox, the **App Options** does not mention the available form factors, but when I install version 2.2 into a scratch org, the **App Options** does mention the available form factors.

_Your Sandbox_

![image](https://user-images.githubusercontent.com/4142577/61608827-cc1b1e80-ac19-11e9-9c7b-2e757b2730f1.png)

_My Scratch Org_

![image](https://user-images.githubusercontent.com/4142577/61608810-bc033f00-ac19-11e9-8b7c-115b982f2d66.png)

The **App Options** are read-only in the org where the managed package is installed and are supposed to be upgradeable by the package (which is what I experience when upgrading the package in scratch orgs), but the fact that the form factors aren't shown at all in your sandbox makes me think there might be an underlying feature/setting disabled in the org. I recommend you reach out to Salesforce Support and see if they can dig deeper to the root cause and enable the necessary functionality.

**Comment by douglascayers** [comment]
A rather intrusive workaround is to uninstall Mass Action Scheduler then install the newer version.

# Workaround: Reinstalling Package

These steps walk through backing up your data and customizations to Mass Action Scheduler package, uninstalling the package, then installing the latest version. Consider this an extreme measure and use as a last resort. Test this in a sandbox before ever trying in production. Always make a backup of your data and metadata before attempting in a production org.

## Install Salesforce CLI

https://developer.salesforce.com/tools/sfdxcli

## Authenticate with Salesforce CLI

Log in to your Salesforce org with the Salesforce CLI. Open Command Prompt (Windows) or Terminal (Mac) to run the following commands.

For sandbox orgs:

```
sfdx force:auth:web:login --setalias myorg --instanceurl https://test.salesforce.com
```

For production orgs:

```
sfdx force:auth:web:login --setalias myorg --instanceurl https://login.salesforce.com
```

## Backup Metadata

If you've created custom fields, list views, reports, Lightning pages, buttons, etc. for the Mass Action Scheduler objects or components, you must delete them before the package can be uninstalled. If you wish to preserve your changes, retrieve the metadata from your org so that you can redeploy them back to your org later.

> If you are unsure how to do this, then I recommend you stop and wait for a better alternative to upgrading Mass Action Scheduler becomes available.

## Export Mass Action Scheduler Data with Salesforce CLI

Export Mass Action Scheduler data with Salesforce CLI in a way that preserves relationships
between the configurations and field mappings so they can be reimported easily later.

The following command queries for all fields part of the Mass Action Scheduler package for the
Mass Action Configuration, Mass Action Field Mapping, and Mass Action Log objects.

If you've created custom fields on any of those objects and if you want to preserve that data,
modify the SOQL query to select your custom fields.

The data is exported to a folder named **mas-data**.

```
sfdx force:data:tree:export --query "SELECT Id, Name, OwnerId, dca_mass_action__Active__c, dca_mass_action__Batch_Size__c, dca_mass_action__Description__c, dca_mass_action__DeveloperName__c, dca_mass_action__Last_Run_Completed_Date__c, dca_mass_action__Last_Run_Completed_With_Errors__c, dca_mass_action__Named_Credential__c, dca_mass_action__Schedule_Cron__c, dca_mass_action__Schedule_DayOfMonth__c, dca_mass_action__Schedule_DayOfWeek__c, dca_mass_action__Schedule_Frequency__c, dca_mass_action__Schedule_HourOfDay__c, dca_mass_action__Schedule_MinuteOfHour__c, dca_mass_action__Schedule_MonthOfYear__c, dca_mass_action__Schedule_SecondOfMinute__c, dca_mass_action__Source_Apex_Class__c, dca_mass_action__Source_List_View_ID__c, dca_mass_action__Source_Report_Column_Name__c, dca_mass_action__Source_Report_ID__c, dca_mass_action__Source_SOQL_Query__c, dca_mass_action__Source_Type__c, dca_mass_action__Target_Action_Name__c, dca_mass_action__Target_Apex_Script__c, dca_mass_action__Target_SObject_Type__c, dca_mass_action__Target_Type__c, ( SELECT Id, dca_mass_action__Source_Field_Name__c, dca_mass_action__Target_Field_Name__c FROM dca_mass_action__Mass_Action_Mappings__r ), ( SELECT Id, dca_mass_action__Job_ID__c, dca_mass_action__Message__c, dca_mass_action__Long_Message__c, dca_mass_action__Submitted_Date__c, dca_mass_action__Total_Batches__c, dca_mass_action__Processed_Batches__c, dca_mass_action__Failed_Batches__c FROM dca_mass_action__Mass_Action_Logs__r ) FROM dca_mass_action__Mass_Action_Configuration__c" --outputdir mas-data --targetusername myorg
```

## Deactivate Processes and Flows

Deactivate all processes and flows that are part of or rely on Mass Action Scheduler packaged objects or components.

## Delete Custom Lightning Record Pages

_You already backed up your metadata first, correct?_

Delete any custom Lightning Record Pages for the objects that are part of the Mass Action Scheduler package.

## Unassign "Mass Action Admin" Permission Set

Unassign the "Mass Action Admin" permission set from all users. Note which users have the permission set.

After installing the new package, you can manually assign the permission set back to the same or different users.

## Uninstall Mass Action Scheduler Package

_Confirm this workaround works in your sandbox org before attempting in production._

1. From Setup, enter `package` in the Quick Find box, click **Installed Packages**.
2. In the Installed Packages section, click **Uninstall** action next to **Mass Action Scheduler** package.
3. Scroll to bottom of the page, select **Yes, I want to uninstall this package**.
4. Click **Uninstall**.

It may take a few minutes for the package to uninstall.

## Install Mass Action Scheduler Package

1. Install the latest version of the Mass Action Scheduler app from the [release notes](https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Release-Notes) page.
2. Assign the **Mass Action Admin** permission set to users who will configure mass actions.

## Deploy Metadata

If you backed up any custom metadata before uninstalling the package, you can redeploy it now.

## Import Mass Action Scheduler Data with Salesforce CLI

```
sfdx force:data:tree:import -f mas-data/dca_mass_action__Mass_Action_Configuration__c-dca_mass_action__Mass_Action_Mapping__c-dca_mass_action__Mass_Action_Log__c.json
```

**Comment by douglascayers** [comment]
@jensanald Regarding the Named Credential error. Make sure the **Mass Action Test Named Credential** looks just like the following screenshot:

![image](https://user-images.githubusercontent.com/4142577/61609981-6466d280-ac1d-11e9-8e17-19c81f3eb95e.png)

**Comment by cchrisv** [comment]
I went ahead and submitted a support ticket to Salesforce.

**Comment by jensanald** [comment]
I also submitted a support ticket. I could not find any info about enabling
form factor options in the app settings. I no longer receive the MA
credential error but now I am receiving the form factor errors.

**Comment by cwland** [comment]
Following, I tried to upgrade to 2.3 this morning and I'm receiving the same error message. 

Error Number: 2122421919-124657 (-44047238)
Problem:

1. (Mass_Action_Scheduler_Lightning) Small is not a supported form factor.
Mass_Action_Scheduler_Lightning: Small is not a supported form factor.

2. (Mass_Action_Configuration__c) Small is not a supported form factor.
Mass_Action_Configuration__c: Small is not a supported form factor.

3. (Mass_Action_Log__c) Small is not a supported form factor.
Mass_Action_Log__c: Small is not a supported form factor.

**Comment by douglascayers** [comment]
ok, I think I've found the culprit. In Summer '19, Developer Edition orgs (where managed packages must be developed and created) had a **pilot** feature auto-enabled: [Get Lightning Experience on Your Phone with Lightning on Mobile (Pilot)](https://releasenotes.docs.salesforce.com/en-us/summer19/release-notes/rn_general_new_mobile_app_pilot.htm)

This made the "Small form factor" available and so the metadata packaged in version 2.3 of the app assumes this pilot feature is available. In customer production and sandbox orgs, this pilot feature is not enabled by default. And as a pilot feature, customers shouldn't enable this in their production orgs anyways.

I will work on disabling this feature in my packaging org and release a new package version. Hopefully that will resolve the issue.

**Comment by cchrisv** [comment]
Your request to install package "Mass Action Scheduler 2.3.1" was successful!

**Comment by cwland** [comment]
I was able to upgrade successfully also.  The question, was the valid query button removed on purpose?  I just noticed it was gone when I was testing.

**Comment by jensanald** [comment]
Hi there, I successfully upgraded as well! Thank you so much!

**Comment by douglascayers** [comment]
Awesome! Glad we got the package fixed!

Thanks everyone for the feedback and assistance.

**Comment by douglascayers** [comment]
Going forward, I'll be testing with "Enterprise" edition scratch orgs instead of "Developer" edition ones, as I was able to reproduce this issue in an EE scratch org.
