### ISSUE TITLE
Somewhat incorrect error displayed for Restricted IP

### ISSUE THREAD

**Issue by ingotlsc** [douglascayers-org/sfdx-mass-action-scheduler#122]
## Summary

Mass Action stopped working due to restricted IP, but the error message stated as below.  Took me a while to notice the login history showing the restricted ip notice.  Added the new IP to our whitelist and everything started working again.  Not sure if you can show the correct error here or not.  Thought I would pass this on.

Was getting errors on the mass action page in Browser Console as well prior to updating IP address.  Did not change anything with auth prov, named cred, etc.  Only updated IP to resolve issue.

Recieved error log:
Error: System.HttpResponse[Status=Unauthorized, StatusCode=401]
[{"message":"Session expired or invalid","errorCode":"INVALID_SESSION_ID"}]
System.HttpRequest[Endpoint=callout:Mass_Action/actions/custom/flow/Create_New_Email_Send_Job, Method=POST]
{

## Version of Mass Action Scheduler

v1.6.  Will be upgrading to the new version after noticing the new features in your latest version.

**Comment by douglascayers** [comment]
Hi @ingotlsc, thanks for sharing this feedback. Unfortunately, the error you see is the response I get back from the API. I don’t believe I’d have another way to know the underlying issue.

I’m glad you figured it out, this seems like something worth adding to the documentation/faq. 

Since there isn’t something I can do otherwise I’m the app, I’m going to close this. Thanks again for your interest in Mass Action Scheduler

Doug
