### ISSUE TITLE
Spring 20 Org Error - First error: no content to map to Object due to end of input	

### ISSUE THREAD

**Issue by cchrisv** [douglascayers-org/sfdx-mass-action-scheduler#133]
## Summary
Org that was upgraded to Spring 20 is now getting the following error:

## Version of Mass Action Scheduler
 2.301.

## Steps To Reproduce
Update to Winter org to Spring 2020

## Expected Behavior
No error

## Actual Result
Job fails

## Source Type

- [ x] Reports
- [ ] List Views
- [ ] SOQL Queries

## Action Type

- [ x] Process Builder & Flows
- [ ] Workflow Rules
- [ ] Email Alerts
- [ ] Quick Actions
- [ ] Apex

## Does your configuration use Named Credentials?
Yes

**Comment by douglascayers** [comment]
Hi @cchrisv,

To troubleshoot, please provide some steps on how to recreate your configuration, data source, and action.

Also, you might try upgrading to the latest 2.4 release I just put out: https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Release-Notes

Thanks

**Comment by cwland** [comment]
Hi, @douglascayers,

I'm seeing the same message as above in multiple sandboxes.     I'm using a SQL statement and passing values to a flow.   When the process is run I receive 'First error: no content to map to Object due to end of input'.    

I tried to re-create the same MAS suing a report instead of a SQL statement and received the following:
First error: Invoke Action Error: System.HttpResponse[Status=Temporary Redirect, StatusCode=307]
The URL has moved <a href="https://XXXXXX--training.my.salesforce.com/services/data/v47.0/actions/custom/flow/Goal_Plan_Goal_Plan_Create_Process">

Have you seen anything like this before? We haven't changed these sandboxes in sometime beyond upgrading to 2.4.

**Comment by cwland** [comment]
@douglascayers Scratch my last message,  I figure it out.   The named credential the URL was set up as https://XXXXXX-training.C16.my.salesforce.com, after seeing the re-direct error I changed it to https://XXXXXX-training.my.salesforce.com and everything started working again.
