### ISSUE TITLE
Invocable Apex action being passed a null list from MAS

### ISSUE THREAD

**Issue by mikemcneeley** [douglascayers-org/sfdx-mass-action-scheduler#79]
## Summary
Using a SOQL source, a record is successfully retrieved:
> 13:19:32.214 (214999619)|UNKNOWN|NamedCallout[Name=Mass_Action, Status Code=200]
> 13:19:32.215 (215391420)|UNKNOWN|{"totalSize":1,"done":true,"records":[{"attributes":{removed for brevity}]}
> 13:19:32.32 (215521166)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:1518
> 13:19:32.32 (216395341)|CALLOUT_RESPONSE|[885]|System.HttpResponse[Status=OK, StatusCode=200]

When this record is passed into the Invocable method directly via anonymous Apex, the operation succeeds as expected. Additionally, the Named Credential that MAS is using is set up with the same user as is running the anonymous Apex. Finally, other MAS jobs are completing as expected, and there are no authentication errors.

The invocable method's parameter type is List&lt;Account&gt;, but also tried with List&lt;Id&gt;. In either case, the resulting HTTP response is: 

> {"statusCode":"UNKNOWN_EXCEPTION","message":"An Apex error occurred: System.NullPointerException: Attempt to de-reference a null object","fields":[]}

Debugging the input param immediately in the invocable method shows:
> 13:19:33.0 (2123972)|USER_DEBUG|[29]|DEBUG|accounts::: [ null ]

## Steps To Reproduce
Manually run the MAS configuration

## Expected Behavior
The Invocable method should be passed the sObject

## Actual Result
The Invocable method is passed in as null

## Source Type
- [ ] Reports
- [ ] List Views
- [x] SOQL Queries

## Action Type
- [ ] Process Builder & Flows
- [ ] Workflow Rules
- [ ] Email Alerts
- [ ] Quick Actions
- [x] Apex

## Does your configuration use Named Credentials?
Yes

**Comment by douglascayers** [comment]
Thanks @mikemcneeley, I'll try to reproduce the issue and follow up.

**Comment by douglascayers** [comment]
@mikemcneeley, I believe the issue is due to the data type used for your Invocable Method.

Rather than use List of a standard type like Account or Contact, use a custom class whose properties have the [@InvocableVariable annotation](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_annotation_InvocableVariable.htm).

The [Actions REST API](https://developer.salesforce.com/docs/atlas.en-us.api_action.meta/api_action/actions_obj_apex.htm) only exposes as inputs primitive properties that use @InvocableVariable, and it doesn't seem that SObjects expose their fields that way.

Here's an example invocable class that demonstrates the use of a custom Request class with invocable variables that can be used on the Field Mapping step in Mass Action Configuration.

```
public with sharing class InvocableDemo {

    @InvocableMethod(
        label = 'InvocableDemo'
    )
    public static List<String> execute( List<Request> requests ) {
    
        System.debug( 'InvocableDemo.execute' );
        System.debug( requests );
        
        List<String> names = new List<String>();
    
        for ( Integer i = 0; i < requests.size(); i++ ) {
			Request req = requests[i];
            System.debug( req );
            names.add( req.FirstName + ' ' + req.LastName );
        }
    
        return names;
    }
    
    public class Request {
    
        @InvocableVariable(
            label = 'First Name'
            description = 'Person First Name'
            required = true
        )
        public String firstName;
        
        @InvocableVariable(
            label = 'Last Name'
            description = 'Person Last Name'
            required = false
        )
        public String lastName;
    
    }

}
```

My data source is a SOQL query to retrieve contacts:

![image](https://user-images.githubusercontent.com/4142577/56873330-2b8cd800-69f7-11e9-83b3-24d0b3883fe6.png)

On the field mapping step, I can then map the SOQL query fields to the invocable variable inputs:

![image](https://user-images.githubusercontent.com/4142577/56873344-61ca5780-69f7-11e9-83c8-e503b04fad56.png)
