### ISSUE TITLE
First error: Error: System.HttpResponse[Status=Unauthorized, StatusCode=401] [{"message":"Session expired or invalid","errorCode":"INVALID_SESSION_ID"}]

### ISSUE THREAD

**Issue by firstmallorca** [douglascayers-org/sfdx-mass-action-scheduler#86]
hello when I run the action I always get this error. Do you know how to overpass this please.

Basically I want to update a field within an object with info from another one. I have create the list with the filters and also created the quick action on the object where I want my field to be updated. 

First error: Error: System.HttpResponse[Status=Unauthorized, StatusCode=401]
[{"message":"Session expired or invalid","errorCode":"INVALID_SESSION_ID"}]
System.HttpRequest[Endpoint=callout:Mass_Action/sobjects/pba__Listing__c/listviews/00B1j0000014wYLE...

**Comment by douglascayers** [comment]
Hi @firstmallorca,

Thanks for your interest in Mass Action Scheduler.

The error message says, "Session expired or invalid". It looks like you're using a Named Credential named **Mass_Action**. Since Named Credentials are [optional](https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Release-Notes-v2.0#get-started-faster-with-optional-named-credentials), please try updating the configuration to not select a Named Credential (set the field blank) then re-run the configuration.

If that succeeds, then the issue was definitely with the Named Credential configuration. Likely, the user it referenced is now inactive or it's password has expired or any number of issues. If you still want to use a Named Credential to specify a context user, please see [these instructions](https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Specify-the-Running-User-via-Named-Credentials).

Thanks

**Comment by firstmallorca** [comment]
Many thanks for your help, after updating to the latest release and doing
all the checkings and settings again I was able to make it working.

For any further questions: Please feel free to ask!

<https://www.firstmallorca.com/en>


*Bogdan Pascu*Project Manager
T: +34 971 007 007 <%2B34971+007+007>
www.firstmallorca.com
Central Office
Avenida Tomas Blanes 41
07181 Costa d'en Blanes

E: bp@firstmallorca.com

<https://www.firstmallorca.com/en>
<https://facebook.com/firstmallorca>  <https://twitter.com/First_Mallorca>
<https://www.instagram.com/firstmallorca/?hl=en/>
<https://www.linkedin.com/company/first-mallorca>
<https://www.youtube.com/user/FirstMallorcaVideos>
<https://plus.google.com/116919964567328768594>

» *click here for legal information* «
<https://www.firstmallorca.com/en/content/privacy-policy>

**Comment by douglascayers** [comment]
Good to hear, thanks for the update
